version: "3.7"

services:
  server:
    image: esphome/esphome:2023.12.9@sha256:0ec7b41a9566e7465d17d6eb2c785158eb7e61a131b21eb91a8ff9f4d14f1a4f
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: on-failure
